# Site settings
title: Metropolis to Mountain
clients:
  - name: Hong Kong Tourism Board
    id: hong-kong
    logo: hong-kong.svg
    link: "http://www.discoverhongkong.com/uk/index.jsp?utm_source=Secret%20Escapes&utm_medium=Hub&utm_campaign=Hong%20Kong%20Taiwan&utm_content=Footer%20Logo"
  - name: Taiwan Tourist Bureau
    id: taiwan
    logo: taiwan.svg
    link: "#client-name"

core-se-link: https://www.secretescapes.com/current-sales
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/metropolis-to-mountain" # the subpath of your site, e.g. /blog/
img:     "/metropolis-to-mountain/_assets/img"
css:     "/metropolis-to-mountain/_assets/css"
js:      "/metropolis-to-mountain/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed