# Site settings
title: Metropolis to Mountain
clients:
  - name: the Hong Kong Tourism Board
    id: hong-kong
    logo: hong-kong.svg
    link: "http://www.discoverhongkong.com/uk/index.jsp?utm_source=Secret%20Escapes&utm_medium=Hub&utm_campaign=Hong%20Kong%20Taiwan&utm_content=Footer%20Logo"
  - name: Taiwan Tourism Bureau
    id: taiwan
    logo: taiwan.svg
    link: "https://eng.taiwan.net.tw/"

core-se-link: https://www.secretescapes.com/current-sales
description: >
  From the heady, bustling streets of vibrant Hong Kong to the breathtaking views that await atop Taiwan’s spellbinding mountains, fill your itinerary with an East Asian adventure like no other.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/metropolis-to-mountain" # the subpath of your site, e.g. /blog/
img:     "/metropolis-to-mountain/_assets/img"
css:     "/metropolis-to-mountain/_assets/css"
js:      "/metropolis-to-mountain/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed